# Generated by Django 2.1 on 2018-09-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180918_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='document',
            new_name='image',
        ),
    ]
